### ISSUE TITLE
Add datasets from WP7_ISAC_rainfarm to portal

### ISSUE THREAD

**Issue by maartenplieger** [c3s-magic/c3s-magic-portal#19]
Added datasets from Enrico for WP7_ISAC_rainfarm:

https://portal.c3s-magic.eu/wms?DATASET=WP7_ISAC_rainfarm

Layer is named "pr"

Can be viewed in http://geoservices.knmi.nl/viewer2.0/

http://geoservices.knmi.nl/viewer2.0/?srs=EPSG%3A4326&bbox=-11.102788970573192,26.83513591903307,27.237860085580436,66.16292835974266&service=https%3A%2F%2Fportal.c3s-magic.eu%2Fwms%3FDATASET%3DWP7_ISAC_rainfarm&layer=pr%24image%2Fpng%24true%24anomaly_agreement%2Fbilinear%241%240&selected=0&dims=time$1997-09-08T12:00:00Z&baselayers=naturalearth2$ne_10m_admin_0_countries_simplified

**Comment by earnone** [comment]
Thanks. The link [https://portal.c3s-magic.eu/wms?DATASET=WP7_ISAC_rainfarm](https://portal.c3s-magic.eu/wms?DATASET=WP7_ISAC_rainfarm) is not working.

> ADAGUC Server: Parameter SERVICE missing

**Comment by maartenplieger** [comment]
@earnone, this is actually a correct response. Maybe we can make this message a bit more user friendly.

You can use this link in http://geoservices.knmi.nl/viewer2.0/, go to "Add layers ... " --> "Add custom WMS service" and paste the link in there. This will enable you to view the dataset.

In the magic portal this will be done automatically.

**Comment by nielsdrost** [comment]
Done.
