### ISSUE TITLE
Add tasmax extreme spell duration datasets from @alasdairhunter to portal

### ISSUE THREAD

**Issue by maartenplieger** [c3s-magic/c3s-magic-portal#22]
https://portal.c3s-magic.eu/wms?DATASET=AHUNTER

Preview:
http://geoservices.knmi.nl/viewer2.0/?srs=EPSG%3A4326&bbox=-32.7,24.666665666666667,51.45,83.33333233333335&service=https%3A%2F%2Fportal.c3s-magic.eu%2Fwms%3FDATASET%3DAHUNTER&layer=tasmax_extreme_spell_duration_IPSL-CM5A-LR_rcp26_2020-01-01_2040-12-01.nc%24image%2Fpng%24true%24tasmax-extreme-spell-1%2Fbilinear%241%240&selected=0&dims=time$2040-05-31T23:00:00Z&baselayers=naturalearth2$ne_10m_admin_0_countries_simplified

**Comment by nielsdrost** [comment]
Done.
