### ISSUE TITLE
Add to portal datasets for ISAC metrics

### ISSUE THREAD

**Issue by earnone** [c3s-magic/c3s-magic-portal#23]
List of all ISAC diagnostics with links to relevant ESMValTool issue and reference to datasets stored on google drive. The list follows deliverable names but please note that some functionalities are produced by a common namelist/diagnostics (in bracket).  

@maartenplieger Most output files will hardly be readable by the viewer - will add a brief description: you can have a quick look at the file structure. Is there a size limit for the files that can be loaded?  

--------------------------------------
WP4:
1. blocking metrics and indices (namelist_miles, beta):
[https://github.com/ESMValGroup/ESMValTool/issues/325](https://github.com/ESMValGroup/ESMValTool/issues/325)
Ref_data: ./WP4-6_ISAC_miles/BlockClim_MPI-ESM-P_r1_1950_2005_DJF.nc

2. hydroclimatic intensity (hyint) and extremes (namelist_hyint, beta):
[https://github.com/ESMValGroup/ESMValTool/issues/322](https://github.com/ESMValGroup/ESMValTool/issues/322)
Ref_data: ./WP4-6_ISAC_hyint/hyint_ACCESS1-0_historical_r1i1p1_1990_2005_ALL.nc
Note: lon/lat/time fields for hydroclimatic indices, their multi-year mean ("_mean") and normalised version ("_norm"). 

3. stratosphere-troposphere coupling (namelist_zmnam, alpha):
[https://github.com/ESMValGroup/ESMValTool/issues/327](https://github.com/ESMValGroup/ESMValTool/issues/327)
Ref_data: ./WP4-6_ISAC_zmnam/eofs.nc

4. precipitation quantile bias (namelist_quantilebias, alpha):
[https://github.com/ESMValGroup/ESMValTool/issues/323](https://github.com/ESMValGroup/ESMValTool/issues/323)
Ref_data: ./WP4_ISAC_quantilebias/MPI-ESM-P_historical_r1i1p1_1979-2005_pr_75qb.nc

--------------------------------------
WP5
1. sub-ensemble selection (namelist_ensclus, beta):
[https://github.com/ESMValGroup/ESMValTool/issues/313](https://github.com/ESMValGroup/ESMValTool/issues/313)
Ref_data: ./WP5_ISAC_ensclus/ens_climatologies_pr_5ens_JJA_Eu_hist.nc
Ref_data2: ./WP5_ISAC_ensclus/ens_anomalies_pr_5ens_JJA_Eu_hist.nc
Ref_data3: ./WP5_ISAC_ensclus/ens_extremes_pr_5ens_JJA_Eu_hist.nc

--------------------------------------
WP6
1. trends and significant testing for hyint and extremes (namelist_hyint, beta)
[https://github.com/ESMValGroup/ESMValTool/issues/324](https://github.com/ESMValGroup/ESMValTool/issues/324)
Ref_data: ./WP4-6_ISAC_hyint/hyint_ACCESS1-0_historical_r1i1p1_1990_2005_ALL_tseries_test.nc
Note: timeseries ("_tseries", region/time fields) and trend coefficients+statistics ("_trends", region/coefficients fields) for hydroclimatic indices 

2. teleconnection indices and weather regimes (namelist_miles, beta)
[https://github.com/ESMValGroup/ESMValTool/issues/326](https://github.com/ESMValGroup/ESMValTool/issues/326)
Ref_data: ./WP4-6_miles/RegimesPattern_MPI-ESM-P_r1_1950_2005_DJF
Ref_data2: ./WP4-6_miles/EOFs_MPI-ESM-P_r1_1950_2005_DJF.nc

3.  indices of anular modes (namelist_zmnam):
[https://github.com/ESMValGroup/ESMValTool/issues/332](https://github.com/ESMValGroup/ESMValTool/issues/332)
Ref_data: ./WP4-6_ISAC_zmnam/monthly_pc.nc

--------------------------------------
WP7
1. RainFARM precipitation stochastic downscaling (namelist_rainfarm, beta):
[https://github.com/ESMValGroup/ESMValTool/issues/312](https://github.com/ESMValGroup/ESMValTool/issues/312)
Ref_data: ./WP7_ISAC_rainfarm/rainfarm_output.nc

--------------------------------------

**Comment by maartenplieger** [comment]
I have copied the contents from the google drive and I have enabled the autowms functionality of adaguc, the directories can now be browsed in the adaguc-viewer.

To browse the work package directories and visualize containing NetCDF files:
1) Go to http://portal.c3s-magic.eu:8080/adaguc-viewer
2) Click the big gear (second main tab) and click AutoWMS. On the right a new pane opens with the current folder structure.
3) You can browse the folders (structured as the work packages) and click on the files.  When a NC file opens, the visualizable layers are displayed.
5) If you click on an image, the layer is added to the map viewer.

This will show up for example:
http://portal.c3s-magic.eu:8080/adaguc-viewer/#addlayer('https://portal.c3s-magic.eu:443/adagucserver?source=c3smagic%2FWP5_ISAC_ensclus%2Fens_extreme_pr_5ens_JJA_Eu_hist.nc&','ens_extreme')

![screenshot-2018-6-4 viewer](https://user-images.githubusercontent.com/8201298/40903859-2708b860-67d9-11e8-9f61-1e9d247a99ea.png)

**Comment by maartenplieger** [comment]
WP4:
1. blocking metrics and indices (namelist_miles, beta):
[https://github.com/ESMValGroup/ESMValTool/issues/325](https://github.com/ESMValGroup/ESMValTool/issues/325)
Ref_data: ./WP4-6_ISAC_miles/BlockClim_MPI-ESM-P_r1_1950_2005_DJF.nc
**[OK]** http://portal.c3s-magic.eu:8080/adaguc-viewer/#addlayer('https://portal.c3s-magic.eu:443/adagucserver?source=c3smagic%2FWP4-6_ISAC_miles%2FBlockClim_MPI-ESM-P_r1_1950_2005_DJF.nc&','LongBlockEvents')

2. hydroclimatic intensity (hyint) and extremes (namelist_hyint, beta):
[https://github.com/ESMValGroup/ESMValTool/issues/322](https://github.com/ESMValGroup/ESMValTool/issues/322)
Ref_data: ./WP4-6_ISAC_hyint/hyint_ACCESS1-0_historical_r1i1p1_1990_2005_ALL.nc
Note: lon/lat/time fields for hydroclimatic indices, their multi-year mean ("_mean") and normalised version ("_norm"). 
**[MISSING]**

3. stratosphere-troposphere coupling (namelist_zmnam, alpha):
[https://github.com/ESMValGroup/ESMValTool/issues/327](https://github.com/ESMValGroup/ESMValTool/issues/327)
Ref_data: ./WP4-6_ISAC_zmnam/eofs.nc
**[Wrong]** Visualizes, but seems to be wrong: http://portal.c3s-magic.eu:8080/adaguc-viewer/#addlayer('https://portal.c3s-magic.eu:443/adagucserver?source=c3smagic%2FWP4-6_ISAC_zmnam%2Feofs.nc&','EOF')


4. precipitation quantile bias (namelist_quantilebias, alpha):
[https://github.com/ESMValGroup/ESMValTool/issues/323](https://github.com/ESMValGroup/ESMValTool/issues/323)
Ref_data: ./WP4_ISAC_quantilebias/MPI-ESM-P_historical_r1i1p1_1979-2005_pr_75qb.nc
**[OK]** http://portal.c3s-magic.eu:8080/adaguc-viewer/#addlayer('https://portal.c3s-magic.eu:443/adagucserver?source=c3smagic%2FWP4_ISAC_quantilebias%2FMPI-ESM-P_historical_r1i1p1_1979-2005_pr_75qb.nc&','pr')
--------------------------------------
WP5
1. sub-ensemble selection (namelist_ensclus, beta):
[https://github.com/ESMValGroup/ESMValTool/issues/313](https://github.com/ESMValGroup/ESMValTool/issues/313)
Ref_data: ./WP5_ISAC_ensclus/ens_climatologies_pr_5ens_JJA_Eu_hist.nc
Ref_data2: ./WP5_ISAC_ensclus/ens_anomalies_pr_5ens_JJA_Eu_hist.nc
Ref_data3: ./WP5_ISAC_ensclus/ens_extremes_pr_5ens_JJA_Eu_hist.nc
**[ALMOST OK]** Is the dimension OK? http://portal.c3s-magic.eu:8080/adaguc-viewer/#addlayer('https://portal.c3s-magic.eu:443/adagucserver?source=c3smagic%2FWP5_ISAC_ensclus%2Fens_anomalies_pr_5ens_JJA_Eu_hist.nc&','ens_anomalies')
--------------------------------------
WP6 
1. trends and significant testing for hyint and extremes (namelist_hyint, beta)
[https://github.com/ESMValGroup/ESMValTool/issues/324](https://github.com/ESMValGroup/ESMValTool/issues/324)
Ref_data: ./WP4-6_ISAC_hyint/hyint_ACCESS1-0_historical_r1i1p1_1990_2005_ALL_tseries_test.nc
Note: timeseries ("_tseries", region/time fields) and trend coefficients+statistics ("_trends", region/coefficients fields) for hydroclimatic indices 
**[MISSING/FAILURE]** Have to look at the files and viewer to see what wrong

2. teleconnection indices and weather regimes (namelist_miles, beta)
[https://github.com/ESMValGroup/ESMValTool/issues/326](https://github.com/ESMValGroup/ESMValTool/issues/326)
Ref_data: ./WP4-6_miles/RegimesPattern_MPI-ESM-P_r1_1950_2005_DJF
Ref_data2: ./WP4-6_miles/EOFs_MPI-ESM-P_r1_1950_2005_DJF.nc

3.  indices of anular modes (namelist_zmnam):
[https://github.com/ESMValGroup/ESMValTool/issues/332](https://github.com/ESMValGroup/ESMValTool/issues/332)
Ref_data: ./WP4-6_ISAC_zmnam/monthly_pc.nc

--------------------------------------
WP7
1. RainFARM precipitation stochastic downscaling (namelist_rainfarm, beta):
[https://github.com/ESMValGroup/ESMValTool/issues/312](https://github.com/ESMValGroup/ESMValTool/issues/312)
Ref_data: ./WP7_ISAC_rainfarm/rainfarm_output.nc
**[OK]** http://portal.c3s-magic.eu:8080/adaguc-viewer/#addlayer('https://portal.c3s-magic.eu:443/adagucserver?source=c3smagic%2FWP7_ISAC_rainfarm%2Frainfarm_output.nc&','pr')

**Comment by earnone** [comment]
Thanks @maartenplieger. I cannot open none of the links you wrote to see the data in the viewer.

I do not understand how the user can select one of the many variables present in the NetCDF file and that the viewer loads simultaneously. I see there are all the colorbar with the units with the units of the various variables but then nothing is shown on the map, nor I can find a selection menu. See e.g. WP4 1. blocking which should not give any trouble.

WP4 point 2 hyint: the data is there in the google drive.

WP6 point 1 hyint timeseries: for timeseries one dimension is time, the second dimension is region code. We may provide an example with only timeseries for one region to avoid the viewer crashing.

WP7 point 1 rainfarm: it would be good to have two windows of the viewer, one for the file at the original resolution and one for the file at the downscaled resolution. Right now it works smooth with the downscaled file. I can provide the original resolution file if that can be done?

**Comment by nielsdrost** [comment]
Done, added all these metrics to the portal.
