### ISSUE TITLE
Portal implementation of shapefileselector tool

### ISSUE THREAD

**Issue by PeterBergSMHI** [c3s-magic/c3s-magic-portal#42]
We want to display the tool for extracting ECV/CII within a user provided shapefile. The metric is in the ESMValTool branch MAGIC_watersector and is called recipe_shapeselect_py.yml

We provide open shapefiles from our own E-HYPE model, and they are stored under esmvaltool/diag_scripts/shapeselect/*.shp  (change path in recipe)

The idea now is to make a portal case where the user can select one of the shapefiles from a dropdown list, select a model and a time period. The portal will then provide the user the option to download the generated netcdf or xlsx files.

PS. There is still work to be done with the recipe, but it is in presentable shape.

Regards,
Peter

**Comment by nielsdrost** [comment]
Done!
