### ISSUE TITLE
Add WP7 droughtmetrics to portal

### ISSUE THREAD

**Issue by PeterBergSMHI** [c3s-magic/c3s-magic-portal#46]
There are now two recipes for drought analysis ready for display in the portal:
recipe_spi.yml
recipe_spei.yml
They are in issue #372 of ESMValTool.

Each recipe produces netcdfs for each model with timeseries on the original time resolution (monthly), but regridded to a reference data set (currently CRUts4.01). In addition, a png-plot is generated which shows a globally averaged histogram of the frequency of each model in different regimes (ranging from "extremely dry" to "extremely wet"), as well as the bias compared to the reference.

The simple visualisation would be to show the pngs, and I suggest we start from there. The interface would be to select:
- a reference data set (default=CRU)
- a set of models (at least one)

**Comment by nielsdrost** [comment]
Done.
